name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set Release Tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t sohanOvaku/demo-github-action:latest .
          docker push sohanOvaku/demo-github-action:latest

          docker build -t sohanOvaku/demo-github-action:latest -t sohanOvaku/demo-github-action:${{ env.RELEASE_TAG }} .
          docker push sohanOvaku/demo-github-action:latest
          docker push sohanOvaku/demo-github-action:${{ env.RELEASE_TAG }}
