name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get Release Assets
        run: |

          REPO_NAME=$(basename ${{ github.repository }})
          LATEST_RELEASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          
          # Extract release tag name
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          echo "Latest release tag is: $TAG_NAME"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
          echo "Latest release tag is: $RELEASE_TAG"

      - name: Show release tag
        run: |
          # Now, in the next step, the RELEASE_TAG will be available
          echo "Latest release tag is: $RELEASE_TAG"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/sohanovaku/demo-github-action:latest -t docker.io/sohanovaku/demo-github-action:$RELEASE_TAG .
          docker push docker.io/sohanovaku/demo-github-action:latest
          docker push docker.io/sohanovaku/demo-github-action:$RELEASE_TAG
          docker save demo-github-action:$RELEASE_TAG | gzip > demo-github-action-$RELEASE_TAG.tar.gz
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload Docker image tar to Google Cloud Storage
        run: |
          gsutil cp demo-github-action-$RELEASE_TAG.tar.gz gs://demo-artifact/demo-github-action-$RELEASE_TAG.tar.gz


