name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get latest release tag
        id: get_release
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          LATEST_RELEASE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest")
          
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          echo "Latest release tag is: $TAG_NAME"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/sohanOvaku/demo-github-action:latest -t docker.io/sohanOvaku/demo-github-action:$RELEASE_TAG .
          docker push docker.io/sohanOvaku/demo-github-action:latest
          docker push docker.io/sohanOvaku/demo-github-action:$RELEASE_TAG

