name: Create Release 

on:
  push:
    branches:
      # target branch
      - master 

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: echo "tag=v1.0.4" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          name: "Release ${{ env.tag }}"
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload hello.txt to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: hello.txt

      # Trigger another action
      - name: Trigger Upload Workflow
              run: |
                curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/upload-to-s3.yml/dispatches \
                -d '{"ref": "master"}'