name: Create Release 

on:
  push:
    branches:
      - master  # Target branch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: echo "tag=v1.0.13" >> $GITHUB_ENV

      - name: Set Variables
        run: echo "ZIP_FILE=hello-${{ env.tag }}.zip" >> $GITHUB_ENV

      - name: Create Zip File
        run: |
          zip "${{ env.ZIP_FILE }}" hello.txt

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          name: "Release ${{ env.tag }}"
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload "${{ env.ZIP_FILE }}" to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: "${{ env.ZIP_FILE }}"
