name: Print Release File Name
on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

    

jobs:
  print-release-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Release Assets
        run: |

          REPO_NAME=$(basename ${{ github.repository }})
          LATEST_RELEASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          
          # Extract release tag name
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')

          # Construct expected zip file name
          ZIP_FILE="hello-$TAG_NAME.zip"

          # Find the browser download URL for the zip file
          ZIP_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "hello-'$TAG_NAME'.zip") | .browser_download_url')

          if [ -z "$ZIP_URL" ] || [ "$ZIP_URL" == "null" ]; then
            echo "No release zip file found!"
            exit 1
          fi

          echo "ZIP_FILE=$ZIP_FILE" 
          echo "ZIP_URL=$ZIP_URL"

