name: Print Release File Name

# on:
#   release:
#     types: [published]

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

    

jobs:
  print-release-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Release Assets
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          
          # Extract release tag name
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')

          # Construct the expected zip file name
          ZIP_FILE="${REPO_NAME}-${TAG_NAME}.zip"

          echo "Release zip file name: $ZIP_FILE"
