name: Print Release File Name

# on:
#   release:
#     types: [published]

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

    

jobs:
  print-release-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Release Assets
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          ZIP_FILE=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | endswith(".zip")) | .name')

          if [ -n "$ZIP_FILE" ]; then
            echo "Release zip file name: $ZIP_FILE"
          else
            echo "No release zip file found"
          fi
