name: Print Release File Name

# on:
#   release:
#     types: [published]

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

    

jobs:
  print-release-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Release Assets
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          ZIP_FILE_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url')
          ZIP_FILE_NAME=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | endswith(".zip")) | .name')

          if [ -z "$ZIP_FILE_URL" ]; then
            echo "No zip file found in release."
            exit 1
          fi

          echo "ZIP_FILE_URL=$ZIP_FILE_URL" >> $GITHUB_ENV
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

          echo "Found release zip file: $ZIP_FILE_NAME"
          echo "Download URL: $ZIP_FILE_URL"
